apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pricecalculatorchart.fullname" . }}
  labels:
    {{- include "pricecalculatorchart.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "pricecalculatorchart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pricecalculatorchart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
