image:
  repository: andreilisovskii/pricecalculator
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: pricecalculator.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []


serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: false